name: 'Google Indexing'
description: 'Index your site on Google using the Indexing API.'
author: 'Robin Genz <mail@robingenz.dev>'

# Define your inputs here.
inputs:
  siteUrl:
    description: 'The domain or site URL of the site to be indexed.'
    required: true
  gcpServiceAccountKey:
    description: 'The GCP service account key in JSON format.'
    required: true
  cacheTimeout:
    description: 'The cache timeout in milliseconds.'
    required: false
    default: 1000 * 60 * 60 * 24 * 7 # 7 days

runs:
  using: node20
  main: dist/index.mjs
